### ISSUE TITLE
Addition of different outputs for `gridinit_cmd`

### ISSUE THREAD

**Issue by cdelgehier** [open-io/gridinit#24]
As the openio cli, could the gridinit output its result by:
* yaml
* json
* csv

Could it only output an attribute of the resource?

example of `-c` and `-f`

`openio account show MYACCOUNT --oio-ns OPENIO -c objects -f yaml`

**Comment by cdelgehier** [comment]
An option to remove the headers of the current output wouldn't be bad too ;)

**Comment by jfsmig** [comment]
Done
